name: Get Next Release Version
description: Determines the next version number based on existing releases
author: Rob Cannon
inputs:
  github-token:
    description: "GitHub auth token"
    default: ${{ github.token }}
  major-minor-version:
    required: false
    description: The Major and Minor version numbers to use
    default: "0.1"
outputs:
  next-version:
    description: The next version to use
runs:
  using: "node16"
  main: "dist/index.js"
