name: Publish Release
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get Next Release Version
        id: get-next-release-version
        uses: acceleratelearning/get-next-release-version-action@v1
        with:
          major-minor-version: "1.0"

      - name: Publish GitHub Release
        id: publish-release
        uses: acceleratelearning/publish-github-release-action@v1
        with:
          version: "${{ steps.get-next-release-version.outputs.next-version }}"
          prefix: v
          add-major-minor-tags: true
